version: 2

jobs:
  test:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: yarn
      - run: yarn lint
      - run: yarn test --maxWorkers=2
  build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: yarn
      - run: yarn build

  release:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run: yarn
      - run: yarn build
      - run: yarn release

workflows:
  version: 2
  test_and_release:
    jobs:
      - test
      - build:
          requires:
            - test
      - release:
          filters:
            branches:
              only: master
          requires:
            - test
            - build
